### ISSUE TITLE
Issues updating after a rename (alpha-22 and up)

### ISSUE THREAD

**Issue by scaleddynamics** [opulencephp/Opulence#1]
Reproduction steps:
1. Create a new project
2. Rename it
3. Watch your world a-splode

  [RuntimeException]
  Error Output: PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Boots
  trappers/Caching/FileCache.php on line 78
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 82
  PHP Warning:  Illegal string offset 'bootstrapper' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers
  /Caching/FileCache.php on line 83
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 78
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 82
  PHP Warning:  Illegal string offset 'bootstrapper' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers
  /Caching/FileCache.php on line 83
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 78
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 82
  PHP Warning:  Illegal string offset 'bootstrapper' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers
  /Caching/FileCache.php on line 83
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 78
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 82
  PHP Warning:  Illegal string offset 'bootstrapper' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers
  /Caching/FileCache.php on line 83
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 78
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 82
  PHP Warning:  Illegal string offset 'bootstrapper' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers
  /Caching/FileCache.php on line 83
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 78
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 82
  PHP Warning:  Illegal string offset 'bootstrapper' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers
  /Caching/FileCache.php on line 83
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 78
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 82
  PHP Warning:  Illegal string offset 'bootstrapper' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers
  /Caching/FileCache.php on line 83
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 78
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 82
  PHP Warning:  Illegal string offset 'bootstrapper' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers
  /Caching/FileCache.php on line 83
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 78
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 82
  PHP Warning:  Illegal string offset 'bootstrapper' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers
  /Caching/FileCache.php on line 83
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 78
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 82
  PHP Warning:  Illegal string offset 'bootstrapper' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers
  /Caching/FileCache.php on line 83
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 78
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 82
  PHP Warning:  Illegal string offset 'bootstrapper' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers
  /Caching/FileCache.php on line 83
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 78
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 82
  PHP Warning:  Illegal string offset 'bootstrapper' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers
  /Caching/FileCache.php on line 83
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 78
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 82
  PHP Warning:  Illegal string offset 'bootstrapper' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers
  /Caching/FileCache.php on line 83
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 78
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 82
  PHP Warning:  Illegal string offset 'bootstrapper' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers
  /Caching/FileCache.php on line 83
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 78
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 82
  PHP Warning:  Illegal string offset 'bootstrapper' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers
  /Caching/FileCache.php on line 83
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 78
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 82
  PHP Warning:  Illegal string offset 'bootstrapper' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers
  /Caching/FileCache.php on line 83
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 78
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 82
  PHP Warning:  Illegal string offset 'bootstrapper' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers
  /Caching/FileCache.php on line 83
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 78
  PHP Warning:  Illegal string offset 'target' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers/Cachi
  ng/FileCache.php on line 82
  PHP Warning:  Illegal string offset 'bootstrapper' in /var/www/html/vendor/opulence/opulence/src/Opulence/Bootstrappers
  /Caching/FileCache.php on line 83
  PHP Fatal error:  Uncaught exception 'Opulence\Ioc\IocException' with message 'Opulence\Views\Caching\ICache is not ins
  tantiable' in /var/www/html/vendor/opulence/opulence/src/Opulence/Ioc/Container.php:171
  Stack trace:
  #0 /var/www/html/vendor/opulence/opulence/src/Opulence/Ioc/Container.php(221): Opulence\Ioc\Container->make('Opulence\\
  Views\\...', false, NULL, Array, Array)
  #1 /var/www/html/vendor/opulence/opulence/src/Opulence/Ioc/Container.php(558): Opulence\Ioc\Container->makeShared('Opul
  ence\\Views\\...')
  #2 /var/www/html/vendor/opulence/opulence/src/Opulence/Ioc/Container.php(388): Opulence\Ioc\Container->resolveClass('Op
  ulence\\Framew...', 'Opulence\\Views\\...', false)
  #3 /var/www/html/vendor/opulence/opulence/src/Opulence/Ioc/Container.php(186): Opulence\Ioc\Container->getResolvedParam
  eters('Opulence\\Framew...', Array, Array, false)
  #4 /var/www/html/vendor/opulence/opulence/src/Opulence/Ioc/Container.php(221): Opulence\Ioc\Container->make('Opulence\\
  Framew...', false, NULL, Array, Array)
  #5 /var/www/html/vendor/opul in /var/www/html/vendor/opulence/opulence/src/Opulence/Applications/Tasks/Dispatchers/Disp
  atcher.php on line 37

**Comment by opulencephp** [comment]
This is almost certainly due to the new way bootstrappers are cached in tmp/framework/(http|console)/cachedBootstrapperRegistry.json.  Try manually deleting those files and then running "php apex framework:flushcache".

Creating a new opulence/Project and renaming it presents no issues for me.

**Comment by opulencephp** [comment]
Author wasn't able to replicate issue.  Closing.
