### ISSUE TITLE
Implement PSR-7

### ISSUE THREAD

**Issue by th3fallen** [opulencephp/Opulence#10]
Title says it all http://www.php-fig.org/psr/psr-7/

**Comment by exts** [comment]
https://www.opulencephp.com/docs/1.0/http-middleware

Better off creating a bridge or porting your middleware to what's already there.

**Comment by th3fallen** [comment]
I was suggesting more for others than myself.

**Comment by opulencephp** [comment]
I applaud what FIG tried to do with PSR-7, but I find their interface difficult to use and very easy to write bugs with (immutability, for example).  Their request/response interfaces do not support nearly enough functionality, either.  IMO, it feels like it was designed by architecture astronauts who didn't put much thought into how it will be used and how their design is prone to misuse.

The same goes for their middleware approach.  To me, passing in the response as a parameter feels strange.  If your middleware is designed correctly, it should just be injecting a POPO service to handle most of the logic inside the middleware.  The framework-specific handling of the request and response shouldn't add much development overhead.

I know it's a popular request, and I've thought long and hard about FIG's PSRs.  Although I would love to adopt a framework-agnostic HTTP request/response wrapper, I find their solution lacking.

**Comment by OddGreg** [comment]
Back before it was released, even one of the members of the FIG wrote about its problems. There are other prominent developers who have spoken against adopting it. It is only a recommendation, of course. Here one dissenting view that makes a few good points: https://evertpot.com/psr-7-issues/
