### ISSUE TITLE
Update components, tag version

### ISSUE THREAD

**Issue by xaben** [opulencephp/Opulence#105]
@opulencephp Can you please tag a new minor version, and also update the components as they don't contain the latest fixes?

Thank you.

**Comment by opulencephp** [comment]
I pushed a tag, but I'm currently having some issues with GitHub and subsplit.  I'll try to push out the changes to the individual components as soon as I resolve them.

**Comment by opulencephp** [comment]
I've gotten git subsplit working again. Components are being updated as I write this. I'm going to go ahead and close this issue. Thanks for reporting!

**Comment by opulencephp** [comment]
FYI all components should be updated now.
