### ISSUE TITLE
Fixing phan issues

### ISSUE THREAD

**Issue by peteraba** [opulencephp/Opulence#113]
Hi @davidbyoung,

I'm using [phan](https://github.com/phan/phan) to improve my code and decided to check Opulence with it. It found a lot of problems, most of them are related to confusing PHPDoc comments.

I'd be happy to contribute fixes for the issues, if you're interested in fixing them.

[phan.txt](https://github.com/opulencephp/Opulence/files/3502798/phan.txt)

**Comment by davidbyoung** [comment]
I'm curious if most of these have been fixed in `develop` when I enabled strict types.  If you run phan on `develop`, are you seeing all these errors, still?

**Comment by peteraba** [comment]
It's almost the same, 1004 lines instead of 1025.

[phan-develop.txt](https://github.com/opulencephp/Opulence/files/3504772/phan-develop.txt)

**Comment by davidbyoung** [comment]
OK. Can you open a PR against 1.1 and I can take a look?

**Comment by davidbyoung** [comment]
Closing for now.  Feel free to open a PR with the fixes.
