### ISSUE TITLE
Interacting with the schema using QueryBuilder

### ISSUE THREAD

**Issue by fzaffa** [opulencephp/Opulence#18]
Do you have any interest in expanding the query builder to add the functionality necessary to interact with and modify the database schema? If not, is it because you believe using DDL is a better practice?

**Comment by opulencephp** [comment]
I have no opposition to expanding the query builders to interact with the schema. I simply haven't had time to implement that feature.

**Comment by davidbyoung** [comment]
Closing for now.  This is a big lift to add proper support for all DB drivers.
