### ISSUE TITLE
use two backslashes

### ISSUE THREAD

**Issue by alchimik** [opulencephp/Opulence#36]
![single_backslash](https://cloud.githubusercontent.com/assets/1812902/21081278/1a8ac65c-bffe-11e6-8209-d8c2aa20bc3c.png)

**Comment by opulencephp** [comment]
What are you referring to, specifically?

**Comment by alchimik** [comment]
It is about code style. 
http://stackoverflow.com/a/4764748/1161101

I think to use two backslash in double quotes is a sensible default.

(sorry for my english -_-)

**Comment by opulencephp** [comment]
Closed because I've implemented these changes when I merged your PR in #35
