### ISSUE TITLE
Why $fallBackToUniversalBindings === false in Opulence\Ioc\Container::hasBinding?

### ISSUE THREAD

**Issue by alchimik** [opulencephp/Opulence#38]
https://github.com/opulencephp/Opulence/blob/1.0/src/Opulence/Ioc/Container.php#L139

```` php
$container = new Container();
class Foo {}
$interface = "interface";
$container->bindInstance($interface, new Foo);
$container->for("foo", function (IContainer $container) use ($interface) {
     var_dump($container->hasBinding($interface));         // false
     var_dump(get_class($container->resolve($interface))); // 'Foo'
});
````

hasBinding === false, but we can resolve anyway. I think it's weird.

**Comment by alchimik** [comment]
[related tests](https://github.com/opulencephp/Opulence/blob/1.0/tests/src/Opulence/Ioc/ContainerTest.php#L732-L792)

**Comment by opulencephp** [comment]
Yup, thanks.  Should have a fix out shortly.
