### ISSUE TITLE
Data Mapper command doesn't handle namespaces

### ISSUE THREAD

**Issue by Garbee** [opulencephp/Opulence#4]
Using `php apex make:datamapper Shop\\Product` as a SQL mapper I expect `{app}/app/project/orm/Shop/Product.php` to be created. Instead `{app}/app/project/orm/ShopProduct.php` is the file created. This means your ORM directory is going to get crazily huge on larger projects.

The datamapper creation command should be able to handle namespaces and create the required folder structure for auto-loading.

**Comment by opulencephp** [comment]
Good catch.  This will be fixed by the next beta.

**Comment by opulencephp** [comment]
This was actually due to the fact that Opulence was incorrectly stripping all slashes from input to the $_SERVER["argv"] variable.  What it really needed to do was only escape backslashes in front of quotes.  I've fixed that, and now your renaming should work the way you wanted it to.
