### ISSUE TITLE
Why view cache depends on vars?

### ISSUE THREAD

**Issue by alchimik** [opulencephp/Opulence#41]
https://github.com/opulencephp/Opulence/blob/1.0/src/Opulence/Views/Caching/FileCache.php#L202

This makes the cache useless for dynamic content

**Comment by opulencephp** [comment]
The view cache is caching a _compiled_ view, which is dependent on the variables set within the view.  So, if the view template is `{{ $username }}`, this is transpiled to `<?php echo htmlentities($username); ?>`.  If users `foo` and `bar` load the page, the compiled views would be `foo` and `bar`.  It's those compiled views that the cache is loading.

I think what you might be after is a cache for the transpiled view contents, which does not currently exist.

**Comment by opulencephp** [comment]
To further clarify - I think I need to split the caches out - one for transpiled contents and one for compiled contents.  Currently, a single cache is being used, which means that we'll have to re-transpile a view for each combination of variable values.  The transpiled cache should not be dependent on variables values - only the compiled cache should.

**Comment by alchimik** [comment]
> If users foo and bar load the page, the compiled views would be foo and bar. It's those compiled views that the cache is loading.

I think it is not.

view: resources/views/username.fortune.php
```
{{ $username }}
```

run 1: 
``` php
        $this->view = $this->viewFactory->createView("username");
        $this->view->setVar('username', 'user1');
        return new Response($this->viewCompiler->compile($this->view));
```

run 2: 
``` php
        $this->view = $this->viewFactory->createView("username");
        $this->view->setVar('username', 'user2');
        return new Response($this->viewCompiler->compile($this->view));
```

caches:
- tmp/framework/http/views/07ebd14baf059ebf079bd1903c5841fb
- tmp/framework/http/views/d76eb756c2678439cbc391330a3f9c28

content same
```
<?php echo $__opulenceFortuneTranspiler->sanitize($username); ?>
```

**Comment by alchimik** [comment]
https://github.com/opulencephp/Opulence/blob/1.0/src/Opulence/Views/Compilers/Fortune/Transpiler.php#L191
https://github.com/opulencephp/Opulence/blob/1.0/src/Opulence/Views/Compilers/Fortune/Transpiler.php#L209

Current cache ==  transpiled cache.

**Comment by opulencephp** [comment]
I think the confusion is with the fact that `FortuneTranspiler` is (incorrectly) using an `ICache` rather than some sort of transpiler cache, which wouldn't be dependent on variable values.  `ICache` is meant to grab a view object with evaluated contents (eg `foo`).  So, this is an oversight/bug.

**Comment by opulencephp** [comment]
Btw, on a sidenote - you've been a rockstar contributor!  Thanks for all the PRs/help!!

**Comment by opulencephp** [comment]
The more I think about it, I think we might be able to just scrap the variable component of `ICache` like you suggested.  Let me think about this a little bit and make sure there's not something I'm missing with that approach.
