### ISSUE TITLE
Rename command changes folder name

### ISSUE THREAD

**Issue by Garbee** [opulencephp/Opulence#5]
When executing `php apex app:rename Project App` the folder `project` is renamed `app`. This shouldn't happen. PSR-4 will work just fine if `App` is contained with the `project` folder. The folder-name shouldn't change since all that does is create needless git changes to track that add no benefit.

**Comment by opulencephp** [comment]
How about I make the renaming of the directories optional?  Ie, you'll be prompted with "Do you want to also rename src/{currName} to src/{newName}?"  I think renaming the directory is beneficial if you want your folder structure to match your application namespace.  "Project" is simply a placeholder and not meant to necessarily be the final name of that directory.

**Comment by Garbee** [comment]
SGTM

**Comment by Garbee** [comment]
:fireworks: Thank you!
