### ISSUE TITLE
wrong multibyte string iteration

### ISSUE THREAD

**Issue by alchimik** [opulencephp/Opulence#52]
see http://stackoverflow.com/questions/3666306/how-to-iterate-utf-8-string-in-php

https://github.com/opulencephp/Opulence/blob/1.0/src/Opulence/Console/Responses/Compilers/Lexers/Lexer.php#L32
https://github.com/opulencephp/Opulence/blob/1.0/src/Opulence/Console/Requests/Tokenizers/StringTokenizer.php#L31
maybe somewhere else

**Comment by opulencephp** [comment]
Interesting, I wasn't aware of this issue.  I'll do some more investigation before implementing a fix.  Thanks for pointing this out!

**Comment by opulencephp** [comment]
This was fixed in the latest release.
