### ISSUE TITLE
Ioc container. Remove 'Reference Parameter' support

### ISSUE THREAD

**Issue by alchimik** [opulencephp/Opulence#54]
https://github.com/opulencephp/Opulence/blob/843da068a56951ec0c33a261b664762c749ded32/src/Opulence/Ioc/Container.php#L327-L332

## 1. it doesn't work
I checked: HEAD, v1.0.0, v1.0.0-rc2

### 1.1 test is wrong
`ContainerTest::testResolvingClassWithReferenceParameter` should be something like:
``` php
public function testResolvingClassWithReferenceParameter()
{
    // preparing
    $bar = new Bar();
    $this->container->bindInstance($this->fooInterface, $bar);
    /** @var ConstructorWithReference $instance1 */
    $instance1 = $this->container->resolve($this->constructorWithReference);
    /** @var ConstructorWithReference $withRef2 */
    $instance2 = $this->container->resolve($this->constructorWithReference);
    $this->assertInstanceOf($this->constructorWithReference, $instance1);
    $this->assertInstanceOf($this->constructorWithReference, $instance2);
    $this->assertNotSame($instance1, $instance2);
    $this->assertSame($instance1->getFoo(), $instance2->getFoo());

    // start useful check
    $instance1->setFoo(new Bar());
    $this->assertSame($instance1->getFoo(), $instance2->getFoo());
    $instance2->setFoo(new Bar());
    $this->assertSame($instance1->getFoo(), $instance2->getFoo());
}
``` 

## 2. other containers don't support this
- illuminate/container
- symfony/dependency-injection
but I could be wrong

## 3. this is a really dangerous feature (imho)

**Comment by opulencephp** [comment]
So, you're suggesting to replace https://github.com/opulencephp/Opulence/blob/843da068a56951ec0c33a261b664762c749ded32/src/Opulence/Ioc/Container.php#L327-L332 with `$resolvedParameters[] = $resolvedParameter;`?

**Comment by alchimik** [comment]
> So, you're suggesting to replace https://github.com/opulencephp/Opulence/blob/843da068a56951ec0c33a261b664762c749ded32/src/Opulence/Ioc/Container.php#L327-L332 with $resolvedParameters[] = $resolvedParameter;?

yes, and remove `ContainerTest::testResolvingClassWithReferenceParameter` test
