### ISSUE TITLE
Publish a coding standards document

### ISSUE THREAD

**Issue by connerbw** [opulencephp/Opulence#58]
Hi, great project.

Your code is very consistent but doesn't always match [Symfony / PSR](http://symfony.com/doc/current/contributing/code/standards.html) style. For example: Use of double quotes instead of single quotes even though there is no "$var" inside the string, single line PHPDoc comments for class properties, ...

It would be nice if you could publish a document explaining what style you expect contributors to adhere to.

Bonus points if I could import it into PHPStorm.

Thanks.

![screenshot from 2017-01-10 11-06-58](https://cloud.githubusercontent.com/assets/812192/21813873/96546d5e-d725-11e6-8dd7-0de5266b5e84.png)

**Comment by opulencephp** [comment]
Thanks!  There is _some_ guidance on style here:  https://www.opulencephp.com/docs/1.0/contributing.  I will take a look at converting to single quotes across the board (when feasible).  I prefer single-line PHPDoc for class properties because it makes it easier to read and takes up less space.  Only for properties that require long explanations do I break them into multi-line PHPDocs.  I'll see what I can whip up in terms of a more detailed style guide.

**Comment by alchimik** [comment]
@opulencephp https://styleci.io/?

**Comment by alchimik** [comment]
@opulencephp maybe add [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) config (like [laravel](https://github.com/laravel/framework/blob/5.3/.php_cs))

**Comment by opulencephp** [comment]
@alchimik How does PHP-CS-Fixer work.  When is it run?  And by whom?  Me or the contributor?  Is it used along with a site like styleci.io?

**Comment by alchimik** [comment]
> @alchimik How does PHP-CS-Fixer work. When is it run? And by whom? Me or the contributor? Is it used along with a site like styleci.io?

PHP-CS-Fixer is the usual local program. 
with PHP-CS-Fixer contributor will be able to check the code style locally, before doing 'pull request'
I think styleci uses the PHP-CS-Fixer inside. PHP-CS-Fixer and styleci configs are basically the same.

**Comment by opulencephp** [comment]
Interesting.  I think I might adopt that.  Thanks for the tip!

**Comment by alchimik** [comment]
I use this config (styleci.io):
```
preset: psr2

risky: false

enabled:
  - whitespacy_lines
  - ordered_use
  - unused_use
  - unneeded_control_parentheses
  - standardize_not_equal
  - single_quote
  - remove_lines_between_uses
  - remove_leading_slash_use
  - no_empty_comment
  - duplicate_semicolon
```

**Comment by opulencephp** [comment]
Thanks!  I've started applying this to the repos.

**Comment by connerbw** [comment]
Interesting info.

I created a file named `.php_cs.dist` in the root of the project, something like:

```php
<?php

<?php

return PhpCsFixer\Config::create()
    ->setRiskyAllowed(true)
    ->setRules([
        '@PSR2' => true,
        'risky' => false,
        'single_quote' => true,
        // More rules here: https://github.com/FriendsOfPHP/PHP-CS-Fixer#usage
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->exclude('tests/Fixtures')
            ->in(__DIR__)
    );
```

When I ran `php-cs-fixer fix .` it goes to town. Would be nice to have for users to run this on their own without much hassle.

> PHP-CS-Fixer and styleci configs are basically the same

Unfortunately they don't seem to use the same config keys. The only one I could get working from the styleci.io config posted above was 'single_quote'. There are many equivalents but the key is not identical.

**Comment by alchimik** [comment]
> Unfortunately they don't seem to use the same config keys. The only one I could get working from the styleci.io config posted above was 'single_quote'. There are many equivalents but the key is not identical.

PHP-CS-Fixer v2 is very new. See [v1 doc](https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/1.13#usage)

**Comment by alchimik** [comment]
php-cs-fixer config #69 (for v2)

for styleci.io (absolutely the same, except no_blank_lines_between_imports)
``` yml
preset: psr2

risky: true

enabled:
  - short_array_syntax
  - no_whitespace_in_blank_line
  - ordered_imports
  - no_unused_imports
  - no_unneeded_control_parentheses
  - standardize_not_equals
  - single_quote
  - no_blank_lines_between_imports
  - no_leading_import_slash
  - no_empty_comment
  - no_empty_statement
```

**Comment by opulencephp** [comment]
Thanks @alchimik.  I've included that into the styleci.io config.  I'll take a look at #69 a little later today.

**Comment by connerbw** [comment]
PS: The docs still use "double quote" syntax. Just saying.

**Comment by opulencephp** [comment]
Yeah, that'll take me a bit longer to update since there's no automated way to update code inside of Markdown files.

**Comment by alchimik** [comment]
> PS: The docs still use "double quote" syntax. Just saying.

done - opulencephp/docs#9

**Comment by opulencephp** [comment]
I've included StyleCI and PHP CS Fixer configs.  So, contributors don't have to worry too much about formatting in their PRs.  Because of this, I'm going to close this issue.  Here's the latest documentation about code style:  https://www.opulencephp.com/docs/1.0/contributing#coding-style
