### ISSUE TITLE
Required PHP Extensions

### ISSUE THREAD

**Issue by rdnn** [opulencephp/Opulence#59]
It might be worth considering updating the documentation to list all required PHP extensions. For example, ctype is required and causes a Opulence\Debug\Errors\FatalThrowableError to be thrown if not loaded. So far, here's a list of extensions required (including those required for composer):

- ctype
- dom
- filter
- hash
- json
- mbstring
- openssl
- phar
- session
- tokenizer
- xml

**Comment by opulencephp** [comment]
The following extensions are actually part of the PHP core, so probably don't need to be listed:
* filter
* hash
* phar
* sessions
* tokenizer

The following are bundled extensions, so probably also do not need to be explicitly listed:
* ctype
* json
* mbstring

The following are external extensions, and should be documented:
* dom
* openssl (already documented)
* xml

Can you point me to where the DOM and XML extensions are used in Opulence?

**Comment by rdnn** [comment]
True! filter, hash, phar, session, and tokenizer are part of the PHP core. However, FreeBSD (and perhaps other systems) provide those extensions independently (session, for example, http://www.freshports.org/www/php70-session). The same applies to ctype, json, and mbstring. Might be worth mentioning, maybe not. Not sure how big the FreeBSD audience is..

Regarding DOM/XML, they are only required for phpunit.

**Comment by alchimik** [comment]
I installed mbstring manually (ubuntu 16.04)

**Comment by opulencephp** [comment]
I've included those extensions in the installation docs:  https://www.opulencephp.com/docs#requirements.  Closing this.
