### ISSUE TITLE
apex app:rename accepts bad input, breaks project

### ISSUE THREAD

**Issue by connerbw** [opulencephp/Opulence#62]
I ran:

```
php apex app:rename Project ms-payment
```

and the project was renamed, returned success, but it created code such as:

```
use ms-payment\Application\Bootstrappers\Cache\RedisBootstrapper;
use ms-payment\Application\Bootstrappers\Databases\SqlBootstrapper;
```

This triggers PHP Parse error:  syntax error, unexpected '-', expecting ',' or ';' 

Expected: Stop me from using a bad name.

**Comment by opulencephp** [comment]
Good catch! Thanks for the report. I'll get a fix out.
