### ISSUE TITLE
\Opulence\Memcached\Memcached methods do not autocomplete in IDE

### ISSUE THREAD

**Issue by connerbw** [opulencephp/Opulence#75]
Copying the example located here:
+ https://www.opulencephp.com/docs/1.0/memcached

I noticed that:

```php
$memcached->set('foo', 'bar');
echo $memcached->get('foo'); // "bar"
```

Are marked as "method not found" in PHPStorm because they use __call(). The documentation for that class seems to imply that I can use any Memcached library i'd like. How many libraries are there other than `\Memcached` and `\Memcache`? How different are the implementations from each other? 

**Feature requests:**

It would be nice to PHPDoc common methods. See:

**_How to get autocomplete for magic method __call:_**
+ http://stackoverflow.com/questions/23605818/how-to-get-autocomplete-for-magic-method-call-php-editors

It would be nice that the `\Opulence\Memcached\Memcached` documentation linked to (and encouraged the use of?) [Memcached Bridge](https://www.opulencephp.com/docs/1.0/cache#memcached-bridge) because if a user stumbles on that page from a search engine maybe they won't know about it.

Similar issues for `\Opulence\Redis\Redis`

**Comment by opulencephp** [comment]
I'll have to think about this.  If PHP supported generics, I'd just open `Memcached` up to being a generic whose type is the client you wish to use.  Although the supported Memcached clients are similar, I cannot guarantee that their interfaces will remain identical.  So, adding intellisense via PHPDoc is risky.

**Comment by connerbw** [comment]
+1 generics. :)

**Comment by opulencephp** [comment]
Per my comment a couple weeks ago, I agree this would be nice, but there's no clean way to do this with multiple client types.  Because of this, I'm going to close this for now.  I appreciate the feedback, though!
