### ISSUE TITLE
Remove deprecated method(s) for forward compatibiltiy

### ISSUE THREAD

**Issue by adelowo** [opulencephp/Opulence#77]
In the [RFC for 7.2 deprecations](https://wiki.php.net/rfc/deprecations_php_7_2), the `each` method was listed as one of the functions/language constructs to be removed in a future PHP version.

I see the function being used in the `Lexer` for ___fortune___.
Relevant links -

-  https://github.com/opulencephp/Opulence/blob/1.0/src/Opulence/Views/Compilers/Fortune/Lexers/Lexer.php#L404

- https://github.com/opulencephp/Opulence/blob/1.0/src/Opulence/Views/Compilers/Fortune/Lexers/Lexer.php#L526

Since this would throw a deprecated notice, i think it's best to be ___cleaned up___ before a general release of the next version. 

Nice work though

**Comment by opulencephp** [comment]
Nice catch.  I'll take a look at how I can achieve the same thing without using deprecated functions.

**Comment by adelowo** [comment]
That would be awesome.

**Comment by davidbyoung** [comment]
This has been finished in 2.0
