### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by Kilgaloon** [opulencephp/Opulence#79]
I'm going through documentation, maybe i'm missing something but i guess there is not migration tool?

**Comment by opulencephp** [comment]
Currently, there is no baked-in DB migration support.  For now, you're free to use a 3rd party migration tool.  I do have plans to support such a feature in the future, though.

**Comment by Kilgaloon** [comment]
I would like to contribute on this part at least, maybe on another parts in future.

**Comment by opulencephp** [comment]
This has been implemented in the [develop branch](https://github.com/opulencephp/Opulence/tree/develop/src/Opulence/Databases/Migrations), and I've added [documentation](https://github.com/opulencephp/docs/blob/1.1/database-migrations.md) (will go up on https://www.opulencephp.com shortly).
