### ISSUE TITLE
Database relation support

### ISSUE THREAD

**Issue by evolic** [opulencephp/Opulence#81]
Can you consider to add database relation support to your ORM?

**Comment by connerbw** [comment]
You can do relations with "Aggregate Roots"

https://www.opulencephp.com/docs/1.0/orm-units-of-work#aggregate-roots

**Comment by evolic** [comment]
I was thinking about following relations:
* 1 to 1
* 1 to many
* many to many

**Comment by creocoder** [comment]
@opulencephp I think it's better to change example in https://www.opulencephp.com/docs/master/orm-units-of-work#aggregate-roots to some more common case. To `User` and `Post` for example.

**Comment by opulencephp** [comment]
@creocoder That's a fair suggestion.  I'll change the example, but `User` and `Post` objects typically aren't created together.  I'll update the example to be an `Order` with multiple `LineItem` objects.

**Comment by creocoder** [comment]
@opulencephp Thanks, great idea!
