### ISSUE TITLE
phpDocumentor problem

### ISSUE THREAD

**Issue by adrix71** [opulencephp/Opulence#95]
Nice framework but unfortunately phpDocumentor does not read the IO\Stream folder probably because Opulence uses reserved names or because it does not support: void as return value. 

Unfortunately I do not know the reason.

Could you resolve please?

Thank you

**Comment by opulencephp** [comment]
Does phpDocumentor support PHP 7.1?  If not, there's not much I can do.

**Comment by adrix71** [comment]
Yes phpDocumentor support PHP 7.1.x or at least all those in php 7.1.x have never given me problems in generating the documentation. Among other things, it is almost certain that the file name will create problems, even if the file Opulence\Http\Response\StreamResponse is generated.

**Comment by opulencephp** [comment]
I'm not too familiar with phpDocumentor.  I reviewed the Stream library, and it's not using any reserved names.  So, I'm not sure why it's having trouble.  If you could point me towards a specific part of the code that's causing problems, that would help me diagnose the issue.

**Comment by adrix71** [comment]
Maybe I expressed myself badly. It is not the library but the name of the file. IStream.php work in phpDocumentor, Stream.php, MultiStream.php, StreamResponse.php and other files witi name or name contain "Stream" no and this is quite a problem because you can not generate the class diagram or anything else that would also help the development of a beautiful and powerful framework.

**Comment by opulencephp** [comment]
That's very strange - why would "Stream" in the filename cause phpDocumentor to not be able to document the code?

**Comment by adrix71** [comment]
Exact but limted on this file. All other file work.

If temporarily move the Stream.php and MultiStream.php files to your desktop, the IStram interface in any other folder and generate the documentation, the interface will also be generated. If I try to move the classes Stream and MultiStream are never generated regardless of where I put them.

It also always reports that the class header is missing on line 0 even if you have entered a comment. Sign that it is probably the name of the file (or directory) that starts or contains Stram not to be fine.

**Comment by opulencephp** [comment]
Interesting.  Since this sounds more like a bug with phpDocumentor (because `Stream` in the filename is perfectly valid), can you instead file a bug with them to fix this?  I'd prefer not to have to change code within the framework to work around a third party library's bug.

**Comment by adrix71** [comment]
I think I'll have to report it. I made the crazy attempt to rename the Stream in Stream directory (it's the Italian translation ... or one of the possible ones) and the files in IRuscello, Ruscello.php and MultiRuscello.php but it does not work the same.

Tomorrow I open the bug to the developers of phpDocumentor, can I indicate the link of the gulub of Opulence as a reference?

**Comment by opulencephp** [comment]
Definitely!  Let me know if they're able to fix it.

**Comment by adrix71** [comment]
Of course I'll let you know. We update you soon.

One thing I wanted to tell you, we are here and I do not think we need to open another topic. 

A couple of years ago I developed a class that relies on PDO and in addition to managing not only MySQL and PostgreSQL but also Microsoft Sql Server, Sqlite, Oracle and IBM DB2 via PDO and also performs the translation of queries between the dialects in a transparent way .

Could it be interesting to implement it in Opulence or do you think it is too much or impossible to manage it with the ORM and the QueryBuilder given the differences between the engines? I'm asking because I have not had time to look deeply into the sources and until this moment I do not know how you've implemented them.

**Comment by opulencephp** [comment]
The reason I haven't tried to support my dialects outside the `QueryBuilders` library is simply due to the fact that it'd be too time consuming for a one-man operation.  I'd rather leave that to a library that's solely dedicated to this sort of thing rather than try to roll it into a full-stack framework.

**Comment by adrix71** [comment]
Ok. Understand :)

We just feel like I know something about phpDocumentor.
