### ISSUE TITLE
Spaces in Path cause passthru to fail for runlocally (possibly others)

### ISSUE THREAD

**Issue by DanSheps** [opulencephp/Opulence#96]
A space in the Windows Path for PHP will cause the run to fail.  Secondary to this issue, no error is reported when running this command.

Paths such as:

c:\Program Files\PHP\7.1\php.exe will result in:

> Running at http://localhost:80
> 'c:\Program' is not recognized as an internal or external command, operable program or batch file.

To reproduce:

Place php in a path on Windows with a space in the path.

To fix:

Test for Windows, test for spaces, encapsulate command path in quotations.

**Comment by opulencephp** [comment]
Interesting.  I'll check this out.  Thanks for reporting!
